package yourpackage.app;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Window {
    private JPanel mainPanelW;
    private JButton playButton;
    private JButton pauseButton;
    private JButton stopButton;
    private JComboBox videoSpeedComboBox;
    private JLabel videoSpeedLabel;
    private JPanel videoPanel;
    private JButton forwardButton;
    private JButton backwardButton;
    private JMenuItem exitButton;
    private JMenu fileButton;
    private JMenuItem openVideoAndDataButton;
    private JMenu editButton;
    private JMenu viewButton;
    private JMenu helpButton;
    private JMenuItem aboutButton;

    public Window() {
        JFrame frame = new JFrame();
        frame.setContentPane(mainPanelW);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setMinimumSize(new Dimension(250, 250));
        frame.setVisible(true);

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        comboBoxModel.addElement("1X");
        comboBoxModel.addElement("5X");
        comboBoxModel.addElement("10X");
        comboBoxModel.addElement("1X Reverse");

        videoSpeedComboBox.setModel(comboBoxModel);
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        openVideoAndDataButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FileSelectionWindow w = FileSelectionWindow.getInstance();
                w.show();
            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanelW = new JPanel();
        mainPanelW.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanelW.add(panel1, BorderLayout.NORTH);
        final JMenuBar menuBar1 = new JMenuBar();
        menuBar1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.add(menuBar1, BorderLayout.CENTER);
        fileButton = new JMenu();
        fileButton.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        fileButton.setText("File");
        menuBar1.add(fileButton);
        openVideoAndDataButton = new JMenuItem();
        openVideoAndDataButton.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        openVideoAndDataButton.setText("Open Video and Data");
        fileButton.add(openVideoAndDataButton);
        exitButton = new JMenuItem();
        exitButton.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        exitButton.setText("Exit");
        fileButton.add(exitButton);
        editButton = new JMenu();
        editButton.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        editButton.setText("Edit");
        menuBar1.add(editButton);
        viewButton = new JMenu();
        viewButton.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        viewButton.setText("View");
        menuBar1.add(viewButton);
        helpButton = new JMenu();
        helpButton.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        helpButton.setText("Help");
        menuBar1.add(helpButton);
        aboutButton = new JMenuItem();
        aboutButton.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        aboutButton.setText("About");
        helpButton.add(aboutButton);
        videoPanel = new JPanel();
        videoPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        videoPanel.setBackground(new Color(-16777216));
        videoPanel.setEnabled(false);
        mainPanelW.add(videoPanel, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 9, new Insets(0, 0, 0, 0), -1, -1));
        mainPanelW.add(panel2, BorderLayout.SOUTH);
        playButton = new JButton();
        playButton.setText("Play");
        panel2.add(playButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pauseButton = new JButton();
        pauseButton.setText("Pause");
        panel2.add(pauseButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stopButton = new JButton();
        stopButton.setText("Stop");
        panel2.add(stopButton, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 8, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        videoSpeedComboBox = new JComboBox();
        panel2.add(videoSpeedComboBox, new GridConstraints(0, 7, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        videoSpeedLabel = new JLabel();
        videoSpeedLabel.setText("Video Speed:");
        panel2.add(videoSpeedLabel, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        forwardButton = new JButton();
        forwardButton.setText("Forward");
        panel2.add(forwardButton, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backwardButton = new JButton();
        backwardButton.setText("Backward");
        panel2.add(backwardButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanelW;
    }

}
